oversion: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            mkdir .kaggle
            cd .kaggle
            echo "{"username":\"${KAGGLE_USERNAME}\","key":\"${KAGGLE_KEY}\}" > kaggle.json
            cd ..
            kaggle competitions download titanic
            jupyter-nbconvert --execute titanic_ml.ipynb
            kaggle competitions submit titanic -f submission.csv -m "My submission"
            mkdir reports
            mv titanic_ml.html reports/
      - store_artifacts:
          path: reports/
          destination: reports/
