oversion: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          command: |
            pipenv install -r requirements.txt --skip-lock
            pipenv lock --pre --clear
      - run:
          command: |
            pipenv run jupyter nbconvert --execute sample_k_neighbors.ipynb
            mkdir -p reports
            mv sample_k_neighbors.html reports/
      - store_artifacts:
          path: reports/
          destination: reports/
