oversion: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            jupyter-nbconvert --execute sample_k_neighbors.ipynb
            mkdir -p reports
            mv sample_k_neighbors.html reports/
      - store_artifacts:
          path: reports/
          destination: reports/
