oversion: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
         #   export KAGGLE_USERNAME
         #   export KAGGLE_KEY
            mkdir -p .kaggle
            cd .kaggle
            echo "{"username":\"${KAGGLE_USERNAME}\","key":\"${KAGGLE_KEY}\}" > kaggle.json
            cd ..
            kaggle competitions download titanic
            jupyter-nbconvert --execute titanic_ml.ipynb
            kaggle competitions submit titanic -f submission.csv -m "My submission"
      #- store_artifacts:
      #    path: reports/
      #    destination: reports/
